spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: boot

kafka:
  #  bootstrap-servers: localhost:9092
  bootstrap-servers: ${spring.embedded.kafka.brokers}
  topic:
    boot: boot.t
